name: metric
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: meangpu
          config_timezone: Asia/Bangkok

          committer_message: "chore: update metrics"
          template: classic
          base: header, activity, community
          plugin_introduction: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
